name: Build Docker Image

on:
  push: # push 到主分支自动 发布
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      # - uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io # 声明镜像源
      #     username: ${{ github.actor }} # 当前github 用户名
      #     password: ${{ secrets.HUB_GITHUB_TOKEN }} # 需要去 https://github.com/settings/tokens 生成一个 名为 token，注意此token 需要读写 packages 等权限 

      - name: Build the  Docker image
        run:
          | # 使用 上一步写的 Dockerfile 构建镜像并发布到私有仓库； 发布完成可以去 https://github.com/MrGaoGang?tab=packages 查看
          docker build . --file Dockerfile --tag dnd:latest 
          docker images
          # docker push ghcr.io/你的github名称/web-image:latest
